spring:
  application:
    name: cilent_producer
eureka:
  client:
#    register-with-eureka: true
    service-url:
      defaultzone: http://localhost:8761/
#  instance:
#    ip-address: http://localhost:8761/eureka/
server:
  port: 9001